export const ADD_NUMBER = 'ADD_NUMBER';
export const MINUS_NUMBER = 'MINUS_NUMBER';
export const MULTIPLICATION_NUMBER = 'MULTIPLICATION_NUMBER';
export const DIVISION_NUMBER = 'DIVISION_NUMBER';


export const GET_USERS_LIST = 'GET_USERS_LIST';